(* Physics/math tests for structural / categorical (ZX, ZW) named operators. *)
cm[x_] := Normal[QuantumOperator[x]["Computational"]["Matrix"]]
cmO[x_, o_] := Normal[QuantumOperator[x, o]["Computational"]["Matrix"]]
comp[x_] := QuantumOperator[x]["Computational"]["Matrix"]
matEq[a_, b_] := Dimensions[a] === Dimensions[b] && Chop[N[a - b], 10^-10] === ConstantArray[0, Dimensions[a]]
symEq[a_, b_] := Dimensions[a] === Dimensions[b] && FullSimplify[a - b] === ConstantArray[0, Dimensions[a]]
unitaryQ[m_] := matEq[m . ConjugateTranspose[m], IdentityMatrix[Length[m]]]
swapDD[d_] := Table[If[{Quotient[i - 1, d], Mod[i - 1, d]} == {Mod[j - 1, d], Quotient[j - 1, d]}, 1, 0], {i, d^2}, {j, d^2}];
ClearAll[ph];

BeginTestSection["Identity and Zero"]
VerificationTest[Normal[QuantumOperator[]["Computational"]["Matrix"]], IdentityMatrix[2], SameTest -> matEq, TestID -> "bare-Identity"]
VerificationTest[cm["Identity"], IdentityMatrix[2], SameTest -> matEq, TestID -> "Identity=I2"]
VerificationTest[cm["I"], IdentityMatrix[2], SameTest -> matEq, TestID -> "I=I2"]
VerificationTest[cm["I"[3]], IdentityMatrix[3], SameTest -> matEq, TestID -> "I[3]"]
VerificationTest[cm["Identity"[{2, 2}]], IdentityMatrix[4], SameTest -> matEq, TestID -> "I[{2,2}]"]
VerificationTest[cm["I"[{2}, {3}]], IdentityMatrix[{2, 3}], SameTest -> matEq, TestID -> "I-rectangular"]
VerificationTest[cm["Zero"], ConstantArray[0, {2, 2}], SameTest -> matEq, TestID -> "Zero=0"]
VerificationTest[cm["O"], ConstantArray[0, {2, 2}], SameTest -> matEq, TestID -> "O=0"]
EndTestSection[]

BeginTestSection["Permutation"]
VerificationTest[cm["Permutation"[{2, 2}, Cycles[{{1, 2}}]]], swapDD[2], SameTest -> matEq, TestID -> "Perm-swap-d2"]
VerificationTest[cm["Permutation"[{3, 3}, Cycles[{{1, 2}}]]], swapDD[3], SameTest -> matEq, TestID -> "Perm-swap-d3"]
VerificationTest[cm["Permutation"[Automatic, {2, 1}]], swapDD[2], SameTest -> matEq, TestID -> "Perm-list-form=swap"]
VerificationTest[cm["Permutation"[{2, 2}, Cycles[{}]]], IdentityMatrix[4], SameTest -> matEq, TestID -> "Perm-identity"]
VerificationTest[unitaryQ[cm["Permutation"[{2, 2, 2}, Cycles[{{1, 2, 3}}]]]], True, TestID -> "Perm-3cycle-unitary"]
VerificationTest[Sort[Round[Re[N[cm["Permutation"[{2, 2, 2}, Cycles[{{1, 2, 3}}]]]]]]], Sort[IdentityMatrix[8]], TestID -> "Perm-3cycle-permutation-matrix"]
EndTestSection[]

BeginTestSection["Curry / Uncurry - inverse reshapes"]
VerificationTest[matEq[Normal[(comp["Curry"[2]] . comp["Uncurry"[2]])], IdentityMatrix[4]], True, TestID -> "Curry.Uncurry=I"]
VerificationTest[matEq[Normal[(comp["Uncurry"[2]] . comp["Curry"[2]])], IdentityMatrix[4]], True, TestID -> "Uncurry.Curry=I"]
VerificationTest[matEq[Normal[(comp["Curry"[3]] . comp["Uncurry"[3]])], IdentityMatrix[9]], True, TestID -> "Curry.Uncurry-d3"]
EndTestSection[]

BeginTestSection["Spider family (ZX / ZW)"]
VerificationTest[cmO["ZSpider"[ph], {1} -> {1, 2}], {{1, 0}, {0, 0}, {0, 0}, {0, Exp[I ph]}}, SameTest -> symEq, TestID -> "ZSpider-1to2"]
VerificationTest[cmO["ZSpider"[ph], {1} -> {1}], {{1, 0}, {0, Exp[I ph]}}, SameTest -> symEq, TestID -> "ZSpider-phase-gate"]
VerificationTest[matEq[cmO["ZSpider"[3/10], {1} -> {1}] . cmO["ZSpider"[1/2], {1} -> {1}], cmO["ZSpider"[8/10], {1} -> {1}]], True, TestID -> "ZSpider-fusion"]
VerificationTest[cmO["XSpider"[6/5], {1} -> {1, 2}], KroneckerProduct[{{1, 1}, {1, -1}} / Sqrt[2], {{1, 1}, {1, -1}} / Sqrt[2]] . {{1, 0}, {0, 0}, {0, 0}, {0, Exp[I 6/5]}} . ({{1, 1}, {1, -1}} / Sqrt[2]), SameTest -> matEq, TestID -> "XSpider=HZSpiderH"]
VerificationTest[cm["Spider"[]], IdentityMatrix[2], SameTest -> matEq, TestID -> "Spider-empty=I"]
VerificationTest[cm["SimpleSpider"[]], IdentityMatrix[2], SameTest -> matEq, TestID -> "SimpleSpider-empty=I"]
VerificationTest[cm["WSpider"[]], {{1, 0, 0, 0}, {0, 1, 1, 0}}, SameTest -> matEq, TestID -> "WSpider-Wnode"]
EndTestSection[]

BeginTestSection["Cup / Cap / snake / Trace"]
VerificationTest[cmO["Cup"[2], {1, 2}], {{1}, {0}, {0}, {1}}, SameTest -> matEq, TestID -> "Cup-2"]
VerificationTest[cmO["Cap"[2], {1, 2}], {{1, 0, 0, 1}}, SameTest -> matEq, TestID -> "Cap-2"]
VerificationTest[Flatten[cmO["Cup"[3], {1, 2}]], Flatten[IdentityMatrix[3]], SameTest -> matEq, TestID -> "Cup-3=vec(I)"]
VerificationTest[Normal[QuantumCircuitOperator[{"Cup"[2] -> {2, 3}, "Cap"[2] -> {1, 2}}]["QuantumOperator", Method -> "Schrodinger"]["Computational"]["Matrix"]], IdentityMatrix[2], SameTest -> matEq, TestID -> "snake=I"]
VerificationTest[cm["Trace"[2]], {{1, 0, 0, 1}}, SameTest -> matEq, TestID -> "Trace-2"]
VerificationTest[cm["Trace"[3]], {Flatten[IdentityMatrix[3]]}, SameTest -> matEq, TestID -> "Trace-3"]
EndTestSection[]

BeginTestSection["Copy / Measure / Encode / Decohere / Marginal / Discard / Reset"]
VerificationTest[cmO["Copy"[2], {1} -> {1, 2}], {{1, 0}, {0, 0}, {0, 0}, {0, 1}}, SameTest -> matEq, TestID -> "Copy-2"]
VerificationTest[cmO["Copy"[3], {1} -> {1, 2}], Transpose[cm["Measure"[3]]], SameTest -> matEq, TestID -> "Copy-3=transpose-Measure"]
VerificationTest[cm["Measure"[2]], {{1, 0, 0, 0}, {0, 0, 0, 1}}, SameTest -> matEq, TestID -> "Measure-2"]
VerificationTest[cm["Measure"[3]], {{1, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 1, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 1}}, SameTest -> matEq, TestID -> "Measure-3"]
VerificationTest[cm["Decohere"[2]], {{1, 0, 0, 0}, {0, 0, 0, 1}}, SameTest -> matEq, TestID -> "Decohere-2"]
VerificationTest[cm["Encode"[2]], Transpose[cm["Measure"[2]]], SameTest -> matEq, TestID -> "Encode=transpose-Measure"]
VerificationTest[cm["Marginal"[3]], {{1, 1, 1}}, SameTest -> matEq, TestID -> "Marginal-3"]
VerificationTest[cm["Discard"[2]], {{1, 1}}, SameTest -> matEq, TestID -> "Discard-2"]
VerificationTest[cm["Discard"[3]], {{1, 1, 1}}, SameTest -> matEq, TestID -> "Discard-3"]
VerificationTest[cm["Reset"["0"]], {{1, 0, 0, 1}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}}, SameTest -> matEq, TestID -> "Reset-0"]
VerificationTest[cm["Reset"["1"]], {{0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {1, 0, 0, 1}}, SameTest -> matEq, TestID -> "Reset-1"]
EndTestSection[]

BeginTestSection["Left / Right / Double - superoperators"]
rhoT = {{1/5, 1/10 + I/10}, {1/10 - I/10, 4/5}};
Amat = {{1, 2}, {3, 4}};
VerificationTest[ArrayReshape[cm["Left"[QuantumOperator[Amat]]] . Flatten[rhoT], {2, 2}], Amat . rhoT, SameTest -> matEq, TestID -> "Left=A.rho"]
VerificationTest[ArrayReshape[cm["Right"[QuantumOperator[Amat]]] . Flatten[rhoT], {2, 2}], rhoT . Amat, SameTest -> matEq, TestID -> "Right=rho.A"]
VerificationTest[ArrayReshape[cm["Double"["S"[]]] . Flatten[rhoT], {2, 2}], cm["S"[]] . rhoT . ConjugateTranspose[cm["S"[]]], SameTest -> matEq, TestID -> "Double=U.rho.Udag"]
EndTestSection[]
