(* ::Package:: *)

(* ============================================================================
   Tests/Stabilizer/GateMatrixForms.wlt -- the stabilizer engine reads a gate
   from its matrix, not its label (QF-B80).

   The engine once decided Clifford membership from the token QuantumShortcut
   derives from a gate's label: a Clifford with no listed name (a bare matrix,
   "I", RX[Pi/2], CY, a transposed S, a machine-precision H) was refused, and a
   non-Clifford carrying a Clifford label was applied as that label, silently.
   Every gate here is fed through the gate entrances in the forms a name-built
   test never produces: label-free matrices, exact and machine and arbitrary
   precision, named gates outside the name list, mislabelled gates, and gates
   on unsorted wires.

   The reference for a gate U is its dense matrix on wires 1..n, built by QF's
   own circuit composition. Each generator X_j, Z_j is conjugated by it and the
   image is named with stabilizerPauliFromMatrix, an exact matrix-to-Pauli-string
   matcher that does not touch the tableau. Applied to the register |0...0>,
   whose destabilizers are X_j and stabilizers Z_j, the engine must hold exactly
   those images: the whole Clifford, signs included, up to a global phase. The
   matcher stops at 4 qubits; larger gates are compared with the same gates
   applied one wire at a time by name, and frames with the dense state.
   ========================================================================== *)

Needs["Wolfram`QuantumFramework`"];
Needs["Wolfram`QuantumFramework`PackageScope`"];


(* Pauli strings and the generators X_1..X_n, Z_1..Z_n. *)
pauliStringMatrix[s_String] := With[{mats = Replace[Characters[s], {"I" -> PauliMatrix[0], "X" -> PauliMatrix[1], "Y" -> PauliMatrix[2], "Z" -> PauliMatrix[3]}, {1}]},
    If[Length[mats] == 1, First[mats], KroneckerProduct @@ mats]
]
generatorStrings[n_Integer] := Join[
    Table[StringJoin @ ReplacePart[ConstantArray["I", n], j -> "X"], {j, n}],
    Table[StringJoin @ ReplacePart[ConstantArray["I", n], j -> "Z"], {j, n}]
]

(* The dense gate on wires 1..n, by QF's circuit composition. *)
denseGate[ops_List, n_Integer] := Normal @ QuantumCircuitOperator[Join[{"I" -> Range[n]}, ops]]["QuantumOperator"]["Matrix"]

(* Expected images of X_1..X_n, Z_1..Z_n under an exact gate, as signed Pauli strings. *)
expectedImages[ops_List, n_Integer] := With[{u = denseGate[ops, n]},
    stabilizerPauliFromMatrix[Simplify[u . pauliStringMatrix[#] . ConjugateTranspose[u]], n] & /@ generatorStrings[n]
]

(* What the engine holds after applying the gates to |0...0>. *)
engineImages[ps_PauliStabilizer] := Join[ps["Destabilizers"], ps["Stabilizers"]]
engineImages[_] := $Failed
tableauImages[ops_List, n_Integer] := engineImages[QuantumCircuitOperator[ops][PauliStabilizer[n]]]

(* Equal as rays: |<u|v>|^2 = <u|u><v|v>, exactly or to machine precision. *)
rayEqQ[u_, v_] := With[{a = Normal[u], b = Normal[v]},
    If[Precision[{a, b}] === Infinity,
        Simplify[(Conjugate[a] . b) (Conjugate[b] . a) - (Conjugate[a] . a) (Conjugate[b] . b)] === 0,
        Chop[Abs[Conjugate[a] . b]^2 - (Conjugate[a] . a) (Conjugate[b] . b), 10^-10] == 0
    ]
]
stabilizerMatchesDenseQ[specs_List] := With[{qc = QuantumCircuitOperator[specs]},
    With[{r = qc[Method -> "Stabilizer"]},
        MatchQ[Head[r], PauliStabilizer | StabilizerFrame] && rayEqQ[r["State"]["StateVector"], qc[]["StateVector"]]
    ]
]

(* The 24 single-qubit Cliffords, up to phase, generated by H and S. *)
$hM = {{1, 1}, {1, -1}} / Sqrt[2];
$sM = {{1, 0}, {0, I}};
$singleQubitCliffords = FixedPoint[
    DeleteDuplicates[
        Join[#, Function[m, With[{p = SelectFirst[Flatten[m], ! PossibleZeroQ[#] &]}, Simplify[m Abs[p] / p]]] /@ Flatten[Outer[Dot, #, {$hM, $sM}, 1], 1]],
        AllTrue[Flatten[Simplify[#1 - #2]], PossibleZeroQ] &
    ] &,
    {IdentityMatrix[2]}
];


(* ============================================================================ *)
(* TIER A -- Cliffords given as matrices                                        *)
(* ============================================================================ *)

VerificationTest[
    Length[$singleQubitCliffords],
    24,
    {},
    TestID -> "GateMatrix-24-SingleQubitCliffords-Fixture"
]

(* Every single-qubit Clifford as a label-free exact matrix, times exact global *)
(* phases written in several forms, including (-1)^(1/4).                       *)
VerificationTest[
    Union @ Flatten @ Map[
        Function[c, With[{expected = expectedImages[{QuantumOperator[c]}, 1]},
            tableauImages[{QuantumOperator[# c]}, 1] === expected & /@ {1, -1, I, (-1)^(1/4), Exp[I Pi / 8], (1 + I) / Sqrt[2], Exp[3 I / 10]}
        ]],
        $singleQubitCliffords
    ],
    {True},
    {},
    TestID -> "GateMatrix-SingleQubitCliffords-ExactMatrices-ExactPhases"
]

(* The same 24 at machine precision, times a machine global phase. *)
VerificationTest[
    Union @ Map[
        tableauImages[{QuantumOperator[N[Exp[3 I / 10] #]]}, 1] === expectedImages[{QuantumOperator[#]}, 1] &,
        $singleQubitCliffords
    ],
    {True},
    {},
    TestID -> "GateMatrix-SingleQubitCliffords-MachinePrecision"
]

(* A 5-digit H is H to its 5 digits, whether its entries are 0.70711 or 1/Sqrt[2]  *)
(* rounded: the two are SameQ and share a cache entry, so each is read first in turn. *)
VerificationTest[
    With[{h5 = {{0.70711`5, 0.70711`5}, {0.70711`5, -0.70711`5}}, h5b = SetPrecision[N[$hM], 5]},
        {
            stabilizerClearCaches[]; Head /@ {QuantumCircuitOperator[{QuantumOperator[h5]}][Method -> "Stabilizer"], QuantumCircuitOperator[{QuantumOperator[h5b]}][Method -> "Stabilizer"]},
            stabilizerClearCaches[]; Head /@ {QuantumCircuitOperator[{QuantumOperator[h5b]}][Method -> "Stabilizer"], QuantumCircuitOperator[{QuantumOperator[h5]}][Method -> "Stabilizer"]}
        }
    ],
    ConstantArray[{PauliStabilizer, PauliStabilizer}, 2],
    {},
    TestID -> "GateMatrix-LowPrecisionH-EitherOrder"
]

(* An exact Clifford whose matrix holds zeros that are not simplified (from        *)
(* composing RX[Pi/2], U3 and CNOT): read with no message.                          *)
VerificationTest[
    With[{u = Normal[QuantumCircuitOperator[{"I" -> Range[3], "H" -> 1, "H" -> 2, "H" -> 3, "RX"[Pi / 2] -> 3, "RX"[Pi / 2] -> 2, "U3"[Pi / 2, 0, Pi] -> 2,
            "CNOT" -> {3, 2}, "U3"[Pi / 2, 0, Pi] -> 2, "CNOT" -> {2, 3}, "RZ"[Pi / 2] -> 2, "RX"[Pi / 2] -> 1, "RZ"[Pi / 2] -> 1, "U3"[Pi / 2, 0, Pi] -> 2,
            "CNOT" -> {2, 3}, "RY"[Pi / 2] -> 1, "U3"[Pi / 2, 0, Pi] -> 3, "CNOT" -> {1, 2}, "CNOT" -> {1, 3}, "RX"[Pi / 2] -> 2, "U3"[Pi / 2, 0, Pi] -> 2,
            "RX"[Pi / 2] -> 3}]["QuantumOperator"]["Matrix"]]},
        tableauImages[{QuantumOperator[u, Range[3]]}, 3] === expectedImages[{QuantumOperator[u, Range[3]]}, 3]
    ],
    True,
    {},
    TestID -> "GateMatrix-ExactClifford-UnsimplifiedZeros"
]

(* A 30-digit X computed as H.Z.H carries a computed zero of precision 0. *)
VerificationTest[
    tableauImages[{QuantumOperator[N[$hM, 30] . N[PauliMatrix[3], 30] . N[$hM, 30]]}, 1],
    expectedImages[{QuantumOperator[PauliMatrix[1]]}, 1],
    {},
    TestID -> "GateMatrix-ArbitraryPrecision-ComputedZero"
]

(* Random multi-qubit Cliffords, label stripped, on wires 1..n. *)
VerificationTest[
    BlockRandom[
        SeedRandom[20261004];
        Union @ Flatten @ Table[
            With[{u = Normal @ QuantumCircuitOperator[Join[Table["H" -> j, {j, n}], Table[
                    If[RandomReal[] < 0.4, "CNOT" -> RandomSample[Range[n], 2], RandomChoice[{"H", "S", "X", "Y", "Z", "V"}] -> RandomInteger[{1, n}]],
                    {12 n}]]]["QuantumOperator"]["Matrix"]},
                With[{expected = expectedImages[{QuantumOperator[u, Range[n]]}, n]},
                    {tableauImages[{QuantumOperator[u, Range[n]]}, n] === expected,
                     tableauImages[{QuantumOperator[N[u], Range[n]]}, n] === expected}
                ]
            ],
            {n, {2, 3}}, {5}
        ]
    ],
    {True},
    {},
    TestID -> "GateMatrix-RandomMultiQubitCliffords-ExactAndMachine"
]

(* Gates on unsorted and sparse wires, and a gate whose output order differs  *)
(* from its input order, placed in a 4-qubit register.                        *)
VerificationTest[
    BlockRandom[
        SeedRandom[20261005];
        With[{u2 = Normal @ QuantumCircuitOperator[{"H" -> 1, "H" -> 2, "CNOT" -> {1, 2}, "S" -> 2, "V" -> 1, "CNOT" -> {2, 1}, "H" -> 2}]["QuantumOperator"]["Matrix"]},
            Map[
                Function[op, tableauImages[{op}, 4] === expectedImages[{op}, 4]],
                {
                    QuantumCircuitOperator[{"CNOT" -> {3, 1}}]["Operators"][[1]],
                    QuantumOperator["C"["Y"]],
                    QuantumOperator[u2, {3, 1}],
                    QuantumOperator[u2, {2, 4}],
                    QuantumOperator[Normal[QuantumOperator["CNOT"]["Matrix"]], {{2, 1}, {1, 2}}]
                }
            ]
        ]
    ],
    {True, True, True, True, True},
    {},
    TestID -> "GateMatrix-UnsortedAndSparseWires"
]


(* ============================================================================ *)
(* TIER B -- named Cliffords the name catalog never listed                      *)
(* ============================================================================ *)

VerificationTest[
    Map[
        Function[op, tableauImages[{op}, Max[2, op["InputOrder"]]] === expectedImages[{op}, Max[2, op["InputOrder"]]]],
        {
            QuantumOperator["I"], QuantumOperator["RX"[Pi / 2]], QuantumOperator["RY"[Pi / 2]], QuantumOperator["RZ"[Pi / 2]],
            QuantumOperator["U3"[Pi / 2, 0, Pi]], QuantumOperator["S"]["Transpose"], QuantumOperator["Y"]["Conjugate"],
            QuantumOperator["V"]["Conjugate"], QuantumOperator["H"]["Dagger"], QuantumOperator["P"[Pi / 2]], QuantumOperator["P"[Pi]]
        }
    ],
    ConstantArray[True, 11],
    {},
    TestID -> "GateMatrix-NamedCliffordsOutsideTheList"
]

(* A Clifford written as a phase gate is a tableau, not a two-component frame: the tableau of S and of Z. *)
VerificationTest[
    {
        engineImages[QuantumCircuitOperator[{"H" -> 1, "P"[Pi / 2] -> 1}][Method -> "Stabilizer"]],
        engineImages[QuantumCircuitOperator[{"H" -> 1, "P"[Pi] -> 1}][Method -> "Stabilizer"]]
    },
    {expectedImages[{"H" -> 1, "S" -> 1}, 1], expectedImages[{"H" -> 1, "Z" -> 1}, 1]},
    {},
    TestID -> "GateMatrix-PhaseGateAtCliffordAngle-IsTableau"
]

(* rz(pi/2) from OpenQASM is S up to a global phase. *)
VerificationTest[
    engineImages[QuantumQASM["OPENQASM 2.0;\ninclude \"qelib1.inc\";\nqreg q[1];\nrz(pi/2) q[0];\n"][PauliStabilizer[1]]],
    expectedImages[{"S" -> 1}, 1],
    {},
    TestID -> "GateMatrix-QASM-RZ-HalfPi-IsS"
]

(* A global phase and a nested circuit change nothing the tableau records. *)
VerificationTest[
    {
        tableauImages[{QuantumOperator["GlobalPhase"[Pi / 3]], "H" -> 1, "CNOT" -> {1, 2}}, 2],
        tableauImages[{QuantumCircuitOperator[{"H" -> 1, "CNOT" -> {1, 2}}], "S" -> 2}, 2]
    },
    {expectedImages[{"H" -> 1, "CNOT" -> {1, 2}}, 2], expectedImages[{"H" -> 1, "CNOT" -> {1, 2}, "S" -> 2}, 2]},
    {},
    TestID -> "GateMatrix-GlobalPhaseAndNestedCircuit"
]


(* ============================================================================ *)
(* TIER C -- the same gate through every gate entrance                          *)
(* ============================================================================ *)

VerificationTest[
    With[{op = QuantumOperator[$hM], plus = expectedImages[{"H" -> 1}, 1]},
        {
            engineImages[QuantumCircuitOperator[{op}][Method -> "Stabilizer"]],
            engineImages[QuantumCircuitOperator[{op}][QuantumState["0"], Method -> "Stabilizer"]],
            engineImages[QuantumCircuitOperator[{op}][PauliStabilizer[1]]],
            engineImages[op[PauliStabilizer[1]]],
            engineImages[PauliStabilizer[QuantumCircuitOperator[{QuantumOperator[N[$hM]]}]]]
        } === ConstantArray[plus, 5]
    ],
    True,
    {},
    TestID -> "GateMatrix-MatrixH-EveryEntrance"
]


(* ============================================================================ *)
(* TIER D -- a label never decides: mislabelled gates are refused or read by    *)
(* their matrix                                                                 *)
(* ============================================================================ *)

$mislabelled = BlockRandom[SeedRandom[1];
    <|"H" -> QuantumOperator["RandomUnitary", "Label" -> "H"], "S" -> QuantumOperator["RandomUnitary", "Label" -> "S"]|>];

VerificationTest[
    QuantumCircuitOperator[{$mislabelled["H"]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-MislabelledH-MethodStabilizer-Refused"
]

VerificationTest[
    $mislabelled["S"][PauliStabilizer[1]],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-MislabelledS-OperatorOnTableau-Refused"
]

VerificationTest[
    PauliStabilizer[QuantumCircuitOperator[{"H" -> 1, $mislabelled["H"]}]],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-MislabelledH-Constructor-Refused"
]

(* A diagonal gate labelled T that is not T, after an H: the phase-polynomial     *)
(* build declines the circuit at the H, before any label check, and the ordinary  *)
(* path applies the phase the gate's matrix carries. The next test reaches the    *)
(* label check.                                                                   *)
VerificationTest[
    With[{qc = QuantumCircuitOperator[{"H" -> 1, QuantumOperator[{{1, 0}, {0, Exp[I Pi / 8]}}, "Label" -> "T"]}]},
        With[{r = qc[Method -> {"Stabilizer", "Compress" -> "PhasePolynomial"}]},
            {Head[r], rayEqQ[r["State"]["StateVector"], qc[]["StateVector"]]}
        ]
    ],
    {StabilizerFrame, True},
    {PauliStabilizer::nophasepoly},
    TestID -> "GateMatrix-MislabelledDiagonal-PhasePolynomial-ReadsMatrix"
]

VerificationTest[
    BlockRandom[SeedRandom[3];
        QuantumCircuitOperator[{QuantumOperator["RandomUnitary", "Label" -> "T"]}][Method -> {"Stabilizer", "Compress" -> "PhasePolynomial"}]
    ],
    $Failed,
    {PauliStabilizer::nophasepoly, PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-MislabelledT-PhasePolynomial-Refused"
]

(* A diagonal-only circuit whose "T" is P[Pi/8]: every token is in the phase-polynomial *)
(* fragment, so only the label check stops the build. The ordinary path then applies   *)
(* the phase the matrix carries: the same frame as P[Pi/8] applied by name, which does  *)
(* not go through the matrix reader (a state check from |00> could not see the phase).  *)
VerificationTest[
    With[{
        r = QuantumCircuitOperator[{QuantumOperator[{{1, 0}, {0, Exp[I Pi / 8]}}, {1}, "Label" -> "T"], "CNOT" -> {1, 2}}][Method -> {"Stabilizer", "Compress" -> "PhasePolynomial"}],
        byName = PauliStabilizer[2]["ApplyCircuit", {"P"[Pi / 8] -> 1, "CNOT" -> {1, 2}}],
        asT = PauliStabilizer[2]["ApplyCircuit", {"P"[Pi / 4] -> 1, "CNOT" -> {1, 2}}]
    },
        {KeyExistsQ[First[r], "PhasePolynomial"], r === byName, r =!= asT}
    ],
    {False, True, True},
    {PauliStabilizer::nophasepoly},
    TestID -> "GateMatrix-MislabelledDiagonal-DiagonalCircuit-PhasePolynomialDeclined"
]

(* Honest labels pass the check at machine precision too: a machine S labelled "S"  *)
(* builds the phase polynomial of the named circuit, with no underflow message.     *)
VerificationTest[
    With[{
        machine = QuantumCircuitOperator[{QuantumOperator[N[{{1, 0}, {0, I}}], {1}, "Label" -> "S"], "CNOT" -> {1, 2}, "T" -> 2}][Method -> {"Stabilizer", "Compress" -> "PhasePolynomial"}],
        named = QuantumCircuitOperator[{"S" -> 1, "CNOT" -> {1, 2}, "T" -> 2}][Method -> {"Stabilizer", "Compress" -> "PhasePolynomial"}]
    },
        {KeyExistsQ[First[machine], "PhasePolynomial"], First[machine]["PhasePolynomial"] === First[named]["PhasePolynomial"]}
    ],
    {True, True},
    {},
    TestID -> "GateMatrix-HonestMachineLabel-PhasePolynomialBuilt"
]


(* ============================================================================ *)
(* TIER H -- the measurement entrance: an observable is measured as its matrix *)
(* ============================================================================ *)

(* An X matrix labelled "Z", measured on |+>, is measured as X: one outcome. The *)
(* references measure a Pauli string by name, ps["M", string], which does not    *)
(* go through the observable reader.                                           *)
VerificationTest[
    With[{plus = PauliStabilizer[1]["H", 1]},
        With[{r = QuantumMeasurementOperator[QuantumOperator[PauliMatrix[1], "Label" -> "Z"]][plus]},
            {r === plus["M", "X"], r =!= plus["M", "Z"], Length[r]}
        ]
    ],
    {True, True, 1},
    {},
    TestID -> "GateMatrix-Measurement-MislabelledObservable-ReadsMatrix"
]

(* The same on unsorted wires of a 3-qubit register: X on wire 3, Z on wire 1, labelled "ZZ". *)
(* On |0, 0, +> the register string Z I X has the certain outcome +1, and a swapped wire  *)
(* order would not.                                                                       *)
VerificationTest[
    With[{ps = PauliStabilizer[3]["H", 3], relabelled = QuantumOperator[QuantumOperator["XZ", {3, 1}], "Label" -> "ZZ"]},
        With[{r = QuantumMeasurementOperator[relabelled][ps]},
            {r === ps["M", "ZIX"], r === QuantumMeasurementOperator[QuantumOperator["XZ", {3, 1}]][ps], Length[r]}
        ]
    ],
    {True, True, 1},
    {},
    TestID -> "GateMatrix-Measurement-MislabelledObservable-UnsortedWires"
]

(* Above the matrix-search cap a label that disagrees with its matrix is not used: *)
(* the measurement takes the dense path.                                           *)
VerificationTest[
    With[{ps = PauliStabilizer[5], x5 = QuantumOperator[KroneckerProduct @@ ConstantArray[PauliMatrix[1], 5], Range[5], "Label" -> "ZZZZZ"]},
        QuantumMeasurementOperator[x5][ps] === QuantumMeasurementOperator[x5][ps["State"]]
    ],
    True,
    {PauliStabilizer::nonpaulibasis},
    TestID -> "GateMatrix-Measurement-MislabelledAboveCap-DensePath"
]

(* An honest label on a machine-precision observable keeps the tableau path. *)
VerificationTest[
    With[{plus = PauliStabilizer[1]["H", 1]},
        QuantumMeasurementOperator[QuantumOperator[N[PauliMatrix[1]], "Label" -> "X"]][plus] === plus["M", "X"]
    ],
    True,
    {},
    TestID -> "GateMatrix-Measurement-HonestMachineObservable-TableauPath"
]


(* ============================================================================ *)
(* TIER E -- what the engine cannot track is refused, with one message          *)
(* ============================================================================ *)

VerificationTest[
    QuantumCircuitOperator[{QuantumOperator["X"[3]]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-Qudit"
]

VerificationTest[
    QuantumCircuitOperator[{QuantumOperator[PauliMatrix[1], {{2}, {1}}]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-GateMovesItsWire"
]

VerificationTest[
    QuantumCircuitOperator[{QuantumOperator[QuantumOperator["H"], QuantumBasis["PauliX"]]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-NonComputationalBasis"
]

VerificationTest[
    QuantumCircuitOperator[{QuantumOperator["RX"[0.3]]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-MachineRotation"
]

VerificationTest[
    QuantumCircuitOperator[{QuantumOperator["Toffoli"]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-Toffoli"
]

VerificationTest[
    QuantumCircuitOperator[{QuantumOperator[2 PauliMatrix[1]]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-NonUnitary"
]

VerificationTest[
    QuantumCircuitOperator[{QuantumOperator["RX"[\[FormalTheta]]]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-SymbolicNonDiagonal"
]

VerificationTest[
    QuantumCircuitOperator[{QuantumOperator[N[$hM] + 10^-6 {{1, 0}, {0, 0}}]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-PerturbedH-NotRoundedToH"
]

VerificationTest[
    PauliStabilizer[1]["ApplyCircuit", {"H" -> 1, "NotAGate" -> 1}],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-ApplyCircuit-UnknownSpec-Refused"
]

(* ps["ApplyCircuit"] still returns a final measurement's outcomes: Z on |+> leaves *)
(* |0> (stabilizer Z) for outcome 0 and |1> (stabilizer -Z) for outcome 1.          *)
VerificationTest[
    With[{r = PauliStabilizer[1]["ApplyCircuit", {"H" -> 1, "M" -> {1}}]},
        {Keys[r], r[0]["Stabilizers"], r[1]["Stabilizers"]}
    ],
    {{0, 1}, {"Z"}, {"-Z"}},
    {},
    TestID -> "GateMatrix-ApplyCircuit-Measurement-Outcomes"
]

VerificationTest[
    PauliStabilizer[1]["ApplyCircuit", {"H" -> 1, "M" -> {1}, "H" -> 1}],
    $Failed,
    {PauliStabilizer::aftermeasurement},
    TestID -> "GateMatrix-ApplyCircuit-GateAfterMeasurement-Refused"
]

(* Non-unitary diagonal matrices, one-qubit and products, are refused, and so are   *)
(* singular ones, each with one PauliStabilizer::nonclifford (the third in one test *)
(* brings General::stop).                                                           *)
VerificationTest[
    QuantumCircuitOperator[{"H" -> 1, QuantumOperator[#]}][Method -> "Stabilizer"] & /@ {{{1, 0}, {0, 2}}, {{1., 0.}, {0., 2.}}, {{2, 0}, {0, 2}}},
    {$Failed, $Failed, $Failed},
    {PauliStabilizer::nonclifford, PauliStabilizer::nonclifford, PauliStabilizer::nonclifford, General::stop},
    TestID -> "GateMatrix-Refused-NonUnitaryDiagonal"
]

VerificationTest[
    QuantumCircuitOperator[{"H" -> {1, 2}, #}][Method -> "Stabilizer"] & /@ {
        QuantumOperator[DiagonalMatrix[{1, 2, 1, 2}], {1, 2}],
        QuantumOperator[KroneckerProduct[$hM, {{1 / 2, 0}, {0, 1}}], {1, 2}]
    },
    {$Failed, $Failed},
    {PauliStabilizer::nonclifford, PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-NonUnitaryProduct"
]

VerificationTest[
    QuantumCircuitOperator[{QuantumOperator[#]}][Method -> "Stabilizer"] & /@ {{{0, 0}, {0, 0}}, {{1, 0}, {0, 0}}},
    {$Failed, $Failed},
    {PauliStabilizer::nonclifford, PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-Singular"
]

(* A matrix that is not unitary is refused as such, whichever step reads it. U = c C, *)
(* a Clifford C times c = 1 + 10^-7, satisfies U P = G U with C's own images G, so    *)
(* only a norm refuses it: a column's in the Clifford test, the factors' scales' in a *)
(* product. The last matrix has columns of norm 1 that are not orthogonal.           *)
VerificationTest[
    stabilizerClearCaches[];
    With[{cnot = {{1, 0, 0, 0}, {0, 1, 0, 0}, {0, 0, 0, 1}, {0, 0, 1, 0}}},
        First[First[stabilizerOperatorSpecs[QuantumOperator[#, Range[Log2[Length[#]]]]]]] & /@ {
            (1 + 10^-7) $hM,
            (1 + 10^-7) cnot,
            (1 + 10^-7) KroneckerProduct[$hM, $hM],
            ConstantArray[0, {4, 4}],
            IdentityMatrix[4] / 2,
            2 cnot,
            DiagonalMatrix[{1, 1, 1, 2}],
            ReplacePart[cnot, {_, 3} -> 0],
            {{1, 1 / Sqrt[2]}, {0, 1 / Sqrt[2]}}
        }
    ],
    ConstantArray["NotUnitary", 9],
    {},
    TestID -> "GateMatrix-Refused-NotUnitary-Reason"
]

(* A diagonal 10^-7 off modulus 1 passes the screen of the Clifford test; the phase   *)
(* step's modulus check refuses it, exact or machine, alone or as a product's factor. *)
VerificationTest[
    QuantumCircuitOperator[{"H" -> {1, 2}, QuantumOperator[#, Range[Log2[Length[#]]]]}][Method -> "Stabilizer"] & /@ {
        {{1, 0}, {0, 1 + 10^-7}},
        N[{{1, 0}, {0, 1 + 10^-7}}],
        KroneckerProduct[{{1, 0}, {0, Exp[I Pi / 4]}}, {{1, 0}, {0, 1 + 10^-7}}]
    },
    {$Failed, $Failed, $Failed},
    {PauliStabilizer::nonclifford, PauliStabilizer::nonclifford, PauliStabilizer::nonclifford, General::stop},
    TestID -> "GateMatrix-Refused-NearlyUnitaryDiagonal"
]

(* An exact gate 10^-10 away from H passes the machine screen; the exact test refuses it. *)
VerificationTest[
    QuantumCircuitOperator[{QuantumOperator[$hM . {{1, 0}, {0, Exp[I / 10^10]}}]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-ExactNearH"
]


(* ============================================================================ *)
(* TIER F -- frames: diagonal non-Cliffords read from the matrix, mixed with   *)
(* multi-qubit Cliffords                                                        *)
(* ============================================================================ *)

VerificationTest[
    stabilizerMatchesDenseQ /@ {
        {"H" -> 1, "CNOT" -> {1, 2}, "T" -> 2},
        {"H" -> 1, QuantumOperator[Normal[QuantumOperator["CNOT"]["Matrix"]], {1, 2}], QuantumOperator["T", {2}]},
        {"H" -> 1, "CNOT" -> {1, 2}, QuantumOperator["RZ"[1. / 3], {2}]},
        {"H" -> 1, "CNOT" -> {1, 2}, "T" -> 2, "H" -> 3, "CNOT" -> {3, 1}, "T" -> 1, "S" -> 3, "CZ" -> {2, 3}},
        {"H" -> 1, QuantumOperator["C"["Y"]], QuantumOperator[{{1, 0}, {0, Cos[1 / 3] + I Sin[1 / 3]}}, {2}]}
    },
    ConstantArray[True, 5],
    {},
    TestID -> "GateMatrix-CliffordPlusDiagonal-MatchesDense"
]

(* A machine phase gate 1e-7 away from S is a phase gate, not S. *)
VerificationTest[
    With[{qc = QuantumCircuitOperator[{"H" -> 1, QuantumOperator[{{1, 0}, {0, Exp[I (Pi / 2 + 10^-7)]}} // N]}]},
        With[{r = qc[Method -> "Stabilizer"]},
            {Head[r], rayEqQ[r["State"]["StateVector"], qc[]["StateVector"]]}
        ]
    ],
    {StabilizerFrame, True},
    {},
    TestID -> "GateMatrix-NearCliffordPhase-StaysPhaseGate"
]

(* A label-free phase gate with a symbolic angle, read from its matrix. *)
VerificationTest[
    With[{r = QuantumCircuitOperator[{"H" -> 1, "CNOT" -> {1, 2}, QuantumOperator[{{1, 0}, {0, Exp[I \[FormalTheta]]}}, {2}]}][Method -> "Stabilizer"]},
        {Head[r], Simplify[Normal[r["State"]["StateVector"]] - {1, 0, 0, Exp[I \[FormalTheta]]} / Sqrt[2]]}
    ],
    {StabilizerFrame, {0, 0, 0, 0}},
    {},
    TestID -> "GateMatrix-SymbolicPhaseGate-FromMatrix"
]

(* A phase whose angle is not provably real (ArcCos[x] is complex for |x| > 1): its *)
(* matrix does not show modulus 1, so it is applied as the one gate its label names, *)
(* whose matrix it is. A wrong label, or none, is refused.                          *)
VerificationTest[
    Map[
        With[{r = QuantumCircuitOperator[{"H" -> 1, "P"[#] -> 1}][Method -> "Stabilizer"]},
            {Head[r], Simplify[Normal[r["State"]["StateVector"]] - {1, Exp[I #]} / Sqrt[2]]}
        ] &,
        {ArcCos[\[FormalX]], Sqrt[\[FormalT]], Log[\[FormalT]]}
    ],
    ConstantArray[{StabilizerFrame, {0, 0}}, 3],
    {},
    TestID -> "GateMatrix-SymbolicPhase-AngleNotProvablyReal"
]

VerificationTest[
    With[{u = Normal[QuantumOperator["P"[ArcCos[\[FormalX]]]]["Matrix"]]},
        QuantumCircuitOperator[{"H" -> 1, #}][Method -> "Stabilizer"] & /@ {QuantumOperator[u, "Label" -> "P"[ArcSin[\[FormalX]]]], QuantumOperator[u]}
    ],
    {$Failed, $Failed},
    {PauliStabilizer::nonclifford, PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-SymbolicPhase-AngleNotProvablyReal-WrongOrNoLabel-Refused"
]


(* ============================================================================ *)
(* TIER I -- one operator on several wires: QF builds "H" -> Range[n] and      *)
(* "T" -> {1, 2} as a single operator, read factor by factor                   *)
(* ============================================================================ *)

(* The 5- and 8-wire H layers equal the same H gates applied one wire at a time   *)
(* by name, at three gate entrances. A product is factored before the full       *)
(* Clifford test, so no size warning.                                             *)
VerificationTest[
    Map[
        Function[n, With[{byName = PauliStabilizer[n]["ApplyCircuit", Table["H" -> j, {j, n}]]},
            Map[
                PauliStabilizerQ[#] && #["Tableau"] === byName["Tableau"] && #["Signs"] === byName["Signs"] &,
                {
                    QuantumCircuitOperator[{"H" -> Range[n]}][Method -> "Stabilizer"],
                    QuantumOperator["H", Range[n]][PauliStabilizer[n]],
                    QuantumCircuitOperator[{"H" -> Range[n]}][PauliStabilizer[n]]
                }
            ]
        ]],
        {5, 8}
    ],
    {{True, True, True}, {True, True, True}},
    {},
    TestID -> "GateMatrix-Product-HadamardLayer-EqualsPerWire"
]

(* Diagonal non-Clifford products, exact and machine, among Cliffords. *)
VerificationTest[
    stabilizerMatchesDenseQ /@ {
        {"H" -> {1, 2}, "T" -> {1, 2}},
        {"H" -> Range[3], "T" -> Range[3], "CNOT" -> {1, 3}, "S" -> Range[3]},
        {"H" -> {1, 2}, QuantumOperator[N[KroneckerProduct[{{1, 0}, {0, Exp[I Pi / 4]}}, {{1, 0}, {0, Exp[I Pi / 8]}}]], {1, 2}]},
        {"H" -> Range[6], "T" -> Range[6], "CZ" -> {2, 5}},
        {"H" -> {1, 2}, QuantumOperator[KroneckerProduct[{{1, 0}, {0, Exp[I Pi / 4]}}, $hM], {1, 2}]},
        {"H" -> {1, 2}, QuantumOperator[N[KroneckerProduct[$hM, {{1, 0}, {0, Exp[I Pi / 8]}}]], {1, 2}]}
    },
    {True, True, True, True, True, True},
    {},
    TestID -> "GateMatrix-Product-DiagonalNonClifford-MatchesDense"
]

(* A symbolic phase gate on two wires, read from its matrix. *)
VerificationTest[
    With[{r = QuantumCircuitOperator[{"H" -> {1, 2}, QuantumOperator["P"[\[FormalTheta]], {1, 2}]}][Method -> "Stabilizer"]},
        {Head[r], Simplify[Normal[r["State"]["StateVector"]] - {1, Exp[I \[FormalTheta]], Exp[I \[FormalTheta]], Exp[2 I \[FormalTheta]]} / 2]}
    ],
    {StabilizerFrame, {0, 0, 0, 0}},
    {},
    TestID -> "GateMatrix-Product-SymbolicPhaseLayer"
]

VerificationTest[
    QuantumCircuitOperator[{"H" -> 1, QuantumOperator[2 KroneckerProduct[{{1, 0}, {0, Exp[I Pi / 4]}}, {{1, 0}, {0, Exp[I Pi / 4]}}], {1, 2}]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Product-Refused-NonUnitary"
]

VerificationTest[
    QuantumCircuitOperator[{QuantumOperator[KroneckerProduct[$hM, Normal[QuantumOperator["RX"[0.3]]["Matrix"]]], {1, 2}]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Product-Refused-NonDiagonalNonCliffordFactor"
]

VerificationTest[
    QuantumCircuitOperator[{"H" -> 1, QuantumOperator["C"["T"], {1, 2}]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-ControlledT"
]

VerificationTest[
    QuantumCircuitOperator[{"H" -> 1, QuantumOperator[{{1, 0}, {0, \[FormalA]}}]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-SymbolicDiagonalNotUnitModulus"
]

VerificationTest[
    QuantumCircuitOperator[{"H" -> 1, QuantumOperator[{{2, 0}, {0, 2 Exp[I \[FormalTheta]]}}]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Refused-SymbolicDiagonalScaled"
]

(* Product specs in the phase-polynomial build: the same polynomial as one wire at a time. *)
VerificationTest[
    With[{
        layer = QuantumCircuitOperator[{"S" -> Range[3], "T" -> {1, 2}, "CZ" -> {1, 3}, "CNOT" -> {1, 2}}][Method -> {"Stabilizer", "Compress" -> "PhasePolynomial"}],
        perWire = QuantumCircuitOperator[{"S" -> 1, "S" -> 2, "S" -> 3, "T" -> 1, "T" -> 2, "CZ" -> {1, 3}, "CNOT" -> {1, 2}}][Method -> {"Stabilizer", "Compress" -> "PhasePolynomial"}]
    },
        {KeyExistsQ[First[layer], "PhasePolynomial"], First[layer]["PhasePolynomial"] === First[perWire]["PhasePolynomial"]}
    ],
    {True, True},
    {},
    TestID -> "GateMatrix-Product-PhasePolynomial-EqualsPerWire"
]

(* A two-wire diagonal labelled "T" (x) "T" whose second factor is P[Pi/8]: declined, then read by its matrix. *)
VerificationTest[
    With[{u = KroneckerProduct[{{1, 0}, {0, Exp[I Pi / 4]}}, {{1, 0}, {0, Exp[I Pi / 8]}}]},
        With[{
            r = QuantumCircuitOperator[{QuantumOperator[u, {1, 2}, "Label" -> QuantumOperator["T", {1, 2}]["Label"]], "CNOT" -> {1, 2}}][Method -> {"Stabilizer", "Compress" -> "PhasePolynomial"}],
            byName = PauliStabilizer[2]["ApplyCircuit", {"P"[Pi / 4] -> 1, "P"[Pi / 8] -> 2, "CNOT" -> {1, 2}}]
        },
            {KeyExistsQ[First[r], "PhasePolynomial"], r === byName}
        ]
    ],
    {False, True},
    {PauliStabilizer::nophasepoly},
    TestID -> "GateMatrix-Product-MislabelledLayer-PhasePolynomialDeclined"
]


(* ============================================================================ *)
(* TIER J -- composite operators: QF composes QuantumOperator["T"] @           *)
(* QuantumOperator["H"] into one operator, read through the gates its label     *)
(* names only when their composition is its matrix                             *)
(* ============================================================================ *)

VerificationTest[
    stabilizerMatchesDenseQ /@ {
        {QuantumOperator["T"] @ QuantumOperator["H"]},
        {"H" -> 1, "CNOT" -> {1, 2}, QuantumOperator["H", {2}] @ QuantumOperator["T", {2}] @ QuantumOperator["H", {2}]},
        {"H" -> 1, QuantumOperator[N[Normal[(QuantumOperator["T"] @ QuantumOperator["H"])["Matrix"]]], "Label" -> ("T" @* "H")]}
    },
    {True, True, True},
    {},
    TestID -> "GateMatrix-Composite-MatchesDense"
]

VerificationTest[
    With[{r = QuantumCircuitOperator[{QuantumOperator["P"[\[FormalTheta]]] @ QuantumOperator["H"]}][Method -> "Stabilizer"]},
        {Head[r], Simplify[Normal[r["State"]["StateVector"]] - {1, Exp[I \[FormalTheta]]} / Sqrt[2]]}
    ],
    {StabilizerFrame, {0, 0}},
    {},
    TestID -> "GateMatrix-Composite-Symbolic"
]

(* The matrix of T.H labelled S @* H: the label's gates do not compose to the matrix. *)
VerificationTest[
    QuantumCircuitOperator[{QuantumOperator[Normal[(QuantumOperator["T"] @ QuantumOperator["H"])["Matrix"]], "Label" -> ("S" @* "H")]}][Method -> "Stabilizer"],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-Composite-Mislabelled-Refused"
]

VerificationTest[
    With[{
        composite = QuantumCircuitOperator[{QuantumOperator["T"] @ QuantumOperator["T"], "CNOT" -> {1, 2}}][Method -> {"Stabilizer", "Compress" -> "PhasePolynomial"}],
        byName = QuantumCircuitOperator[{"T" -> 1, "T" -> 1, "CNOT" -> {1, 2}}][Method -> {"Stabilizer", "Compress" -> "PhasePolynomial"}]
    },
        {KeyExistsQ[First[composite], "PhasePolynomial"], First[composite]["PhasePolynomial"] === First[byName]["PhasePolynomial"]}
    ],
    {True, True},
    {},
    TestID -> "GateMatrix-Composite-PhasePolynomial"
]

(* A machine-precision symbolic phase gate, and a symbolic global phase. *)
VerificationTest[
    {
        With[{r = QuantumCircuitOperator[{"H" -> 1, N[QuantumOperator["P"[\[FormalTheta]]]]}][Method -> "Stabilizer"]},
            {Head[r], Chop[N[Normal[r["State"]["StateVector"]] /. \[FormalTheta] -> 0.7] - N[{1, Exp[0.7 I]} / Sqrt[2]]]}
        ],
        tableauImages[{QuantumOperator["GlobalPhase"[\[FormalTheta]]], "H" -> 1}, 1] === expectedImages[{"H" -> 1}, 1]
    },
    {{StabilizerFrame, {0, 0}}, True},
    {},
    TestID -> "GateMatrix-MachineSymbolicPhase-SymbolicGlobalPhase"
]


(* ============================================================================ *)
(* TIER K -- one Clifford matrix on 5 to 12 wires, not a product: read up to   *)
(* 12 qubits, with PauliStabilizer::largegate from 8 qubits (exact entries) or *)
(* 10 (approximate ones), and refused above the cap. The reference is the same *)
(* gates applied one wire at a time by name.                                   *)
(* ============================================================================ *)

randomCliffordSpecs[n_Integer, m_Integer] := Join[Table["H" -> j, {j, n}], Table[
    If[RandomReal[] < 0.4, "CNOT" -> RandomSample[Range[n], 2], RandomChoice[{"H", "S", "X", "Y", "Z"}] -> RandomInteger[{1, n}]], m]]
cliffordMatrixEqualsNamesQ[specs_List, n_Integer] := With[{
    r = QuantumCircuitOperator[{QuantumOperator[N @ Normal @ QuantumCircuitOperator[specs]["QuantumOperator"]["Matrix"], Range[n]]}][Method -> "Stabilizer"],
    byName = PauliStabilizer[n]["ApplyCircuit", specs]
},
    PauliStabilizerQ[r] && r["Tableau"] === byName["Tableau"] && r["Signs"] === byName["Signs"]
]

VerificationTest[
    BlockRandom[SeedRandom[51]; cliffordMatrixEqualsNamesQ[randomCliffordSpecs[#, 8 #], #] & /@ {5, 6, 7}],
    {True, True, True},
    {},
    TestID -> "GateMatrix-LargeClifford-5to7Qubits"
]

(* The size warning fires once per gate: the caches are cleared so the file can be rerun in one kernel. *)
VerificationTest[
    stabilizerClearCaches[];
    BlockRandom[SeedRandom[52]; cliffordMatrixEqualsNamesQ[randomCliffordSpecs[10, 60], 10]],
    True,
    {PauliStabilizer::largegate},
    TestID -> "GateMatrix-LargeClifford-10Qubits-Warns"
]

VerificationTest[
    stabilizerClearCaches[];
    BlockRandom[SeedRandom[54];
        With[{specs = randomCliffordSpecs[8, 40]},
            With[{
                r = QuantumCircuitOperator[{QuantumOperator[Normal @ QuantumCircuitOperator[specs]["QuantumOperator"]["Matrix"], Range[8]]}][Method -> "Stabilizer"],
                byName = PauliStabilizer[8]["ApplyCircuit", specs]
            },
                PauliStabilizerQ[r] && r["Tableau"] === byName["Tableau"] && r["Signs"] === byName["Signs"]
            ]
        ]
    ],
    True,
    {PauliStabilizer::largegate},
    TestID -> "GateMatrix-LargeClifford-Exact8Qubits-Warns"
]

(* The constructor reads a gate through QuantumOperatorTableau and, when that      *)
(* refuses, again through the gate fold: an exact 8-qubit Clifford times T on wire *)
(* 1 warns once and is refused once.                                              *)
VerificationTest[
    stabilizerClearCaches[];
    BlockRandom[SeedRandom[54];
        With[{c8 = Normal @ QuantumCircuitOperator[randomCliffordSpecs[8, 40]]["QuantumOperator"]["Matrix"]},
            PauliStabilizer[QuantumCircuitOperator[{QuantumOperator[c8 . KroneckerProduct[{{1, 0}, {0, Exp[I Pi / 4]}}, IdentityMatrix[128]], Range[8]]}]]
        ]
    ],
    $Failed,
    {PauliStabilizer::largegate, PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-LargeGate-Constructor-WarnsOnce"
]

VerificationTest[
    BlockRandom[SeedRandom[53];
        Block[{$stabilizerMatrixMaxQubits = 5},
            QuantumCircuitOperator[{QuantumOperator[N @ Normal @ QuantumCircuitOperator[randomCliffordSpecs[6, 40]]["QuantumOperator"]["Matrix"], Range[6]]}][Method -> "Stabilizer"]
        ]
    ],
    $Failed,
    {PauliStabilizer::nonclifford},
    TestID -> "GateMatrix-LargeClifford-AboveCap-Refused"
]


(* ============================================================================ *)
(* TIER G -- on honest named circuits the matrix route equals the name route   *)
(* ============================================================================ *)

VerificationTest[
    BlockRandom[
        SeedRandom[11];
        With[{specs = Table[If[RandomReal[] < 0.4, "CNOT" -> RandomSample[Range[40], 2], RandomChoice[{"H", "S", "X", "Y", "Z"}] -> RandomInteger[{1, 40}]], 600]},
            With[{viaMatrices = QuantumCircuitOperator[specs][Method -> "Stabilizer"], viaNames = PauliStabilizer[40]["ApplyCircuit", specs]},
                PauliStabilizerQ[viaMatrices] && PauliStabilizerQ[viaNames] &&
                    viaMatrices["Tableau"] === viaNames["Tableau"] && viaMatrices["Signs"] === viaNames["Signs"]
            ]
        ]
    ],
    True,
    {},
    TestID -> "GateMatrix-HonestNamedCircuit-MatrixRouteEqualsNameRoute"
]
