#!/usr/bin/env python3
"""Extract the ```wl fenced cells from a solutions .md, in order, into a runnable .wls.

The point is to run the EXACT bytes that ship in the .md, never a hand-copy of them:
a hand-transcribed harness verifies the transcription, not the document.

Usage: extract-cells.py Solutions-Part-03.md verify/part03-cells.wls
"""
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
text = open(src, encoding="utf-8").read()

# section heading -> cell provenance, so a failure names the question it came from
heads = [(m.start(), m.group(1)) for m in re.finditer(r"^### (\S+)", text, re.M)]


def which(pos):
    tag = "?"
    for start, h in heads:
        if start < pos:
            tag = h
        else:
            break
    return tag


cells = [(m.start(), m.group(1)) for m in re.finditer(r"```wl\n(.*?)```", text, re.S)]

with open(dst, "w", encoding="utf-8") as f:
    f.write("(* GENERATED by verify/extract-cells.py from %s. Do not edit. *)\n" % src)
    f.write('WriteString[$Output, "=== extract-and-run: %d cells ===\\n"];\n' % len(cells))
    for i, (pos, body) in enumerate(cells):
        f.write('WriteString[$Output, "=== %s cell %d ===\\n"];\n' % (which(pos), i + 1))
        # Show each cell's VALUE, not merely "no error fired". A cell can hold several
        # expressions on separate lines (notebook style: e.g. `ovl = Integrate[...]` then
        # `Simplify[...]`); wrapping the raw body in `$out = ( ... )` parens would splice
        # those adjacent lines into an implicit Times and, when the first is a Set, a
        # self-reference that recurses. So hand the body to ToExpression as a STRING: it
        # parses newline-separated expressions as a proper statement sequence and returns
        # the LAST value, exactly as a notebook cell does. Named characters (\[Kappa], ...)
        # are valid inside a WL string literal as-is; only `"` needs escaping.
        stripped = body.rstrip().replace("\\", "\\\\").replace('"', '\\"')
        f.write('WriteString[$Output, ToString[ToExpression["')
        f.write(stripped)
        f.write('", InputForm], InputForm], "\\n"];\n')
    f.write('WriteString[$Output, "MD-CELLS-RAN-OK\\n"];\n')

print("%d cells -> %s" % (len(cells), dst))
