name: Build
on: 
  workflow_dispatch:
  push: 
    branches:  [main]
  pull_request_target: 
    branches:  [main]
env: 
  RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
  WLPR_PACLET_SITE: https://resources.wolframcloud.com/PacletRepository/pacletsite
jobs: 
  Build: 
    name: Build
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
    steps: 
    - run: apt-get update && apt-get install -y git-lfs
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v3
      with:
        lfs: true
    - name: Build
      id: build-paclet-step
      uses: WolframResearch/build-paclet@v1.11.0
      with: 
        target: Submit
        check: false
        paclet_cicd_version: 0.36.0
        definition_notebook: ./QuantumFramework/ResourceDefinition.nb
        resource_system_base: https://www.wolframcloud.com/obj/resourcesystem/api/1.0
    - run: |
        wolframscript -code "
        CloudConnect[\"wolframquantumframework@wolfram.com\", \"${{ secrets.WQF_PASSWORD }}\"];
        CopyFile[\"${{env.PACLET_PATH}}\", CloudObject[\"QuantumFramework.paclet\", Permissions -> \"Public\"], OverwriteTarget -> True];
        DeleteDirectory[CloudObject[\"Courses\"], DeleteContents -> True];
        CopyDirectory[\"./Notebooks/Courses\", CloudObject[\"Courses\"]]
        "
